// <auto-generated />
using System;
using MediaByQr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaByQr.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250819162452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MediaByQr.Models.Etkinlik", b =>
                {
                    b.Property<int>("EtkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtkinlikAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EtkinlikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("MediaByQr.Models.Fotograf", b =>
                {
                    b.Property<int>("FotografId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DosyaAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("FotografId");

                    b.HasIndex("EtkinlikId");

                    b.ToTable("Fotograflar");
                });

            modelBuilder.Entity("MediaByQr.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MediaByQr.Models.Etkinlik", b =>
                {
                    b.HasOne("MediaByQr.Models.Kullanici", "Kullanici")
                        .WithMany("Etkinlikler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MediaByQr.Models.Fotograf", b =>
                {
                    b.HasOne("MediaByQr.Models.Etkinlik", "Etkinlik")
                        .WithMany("Fotograflar")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");
                });

            modelBuilder.Entity("MediaByQr.Models.Etkinlik", b =>
                {
                    b.Navigation("Fotograflar");
                });

            modelBuilder.Entity("MediaByQr.Models.Kullanici", b =>
                {
                    b.Navigation("Etkinlikler");
                });
#pragma warning restore 612, 618
        }
    }
}
